/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vista;

import Controlador.Estudiante_Control;
import Modelo.Estudiante;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author henry
 */
public class JfrEditar extends javax.swing.JInternalFrame {

    private DefaultTableModel modelo = new DefaultTableModel();
    private Estudiante_Control est_con = new Estudiante_Control();

    /**
     * Creates new form JfrEditar
     */
    public JfrEditar(JToggleButton a) {
        initComponents();
        addInternalFrameListener(new InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(InternalFrameEvent e) {

                a.setSelected(false);

            }
        });
        jtblEstudiantes.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (jtblEstudiantes.getSelectedRow() != -1) {
                    jtxtCed.setText((String) jtblEstudiantes.getValueAt(jtblEstudiantes.getSelectedRow(), 0));
                    jtxtNom.setText((String) jtblEstudiantes.getValueAt(jtblEstudiantes.getSelectedRow(), 1));
                    jtxtApe.setText((String) jtblEstudiantes.getValueAt(jtblEstudiantes.getSelectedRow(), 2));
                    jtxtDir.setText((String) jtblEstudiantes.getValueAt(jtblEstudiantes.getSelectedRow(), 3));
                    jtxtTel.setText((String) jtblEstudiantes.getValueAt(jtblEstudiantes.getSelectedRow(), 4));
                }
            }
        });
        cargarTabla();
    }

    public void cargarTabla() {

        modelo.setRowCount(0);
        String[] columnas = {"Cedula", "Nombre", "Apellido", "Direccion", "Telefono"};
        modelo.setColumnIdentifiers(columnas);

        ArrayList<Estudiante> registro = est_con.getEstudiantes();
        for (Estudiante est : registro) {
            Object[] lista = {est.getCedula(), est.getNombre(), est.getApellido(), est.getDireccion(), est.getCelular()};
            modelo.addRow(lista);
        }
        jtblEstudiantes.setModel(modelo);
        jtblEstudiantes.getTableHeader().setReorderingAllowed(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        asas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblEstudiantes = new javax.swing.JTable();
        JbtnGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtxtApe = new javax.swing.JTextField();
        jtxtNom = new javax.swing.JTextField();
        jtxtDir = new javax.swing.JTextField();
        jtxtCed = new eddercomponente.EdderComponente();
        jtxtTel = new eddercomponente.EdderComponente();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Editar Estudiante");

        asas.setBackground(new java.awt.Color(204, 255, 255));
        asas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblEstudiantes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jtblEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jScrollPane1.setViewportView(jtblEstudiantes);

        asas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 296, 529, 178));

        JbtnGuardar.setText("Guardar");
        JbtnGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        JbtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnGuardarActionPerformed(evt);
            }
        });
        asas.add(JbtnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 46, 150, 43));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nombre");
        asas.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 78, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Direccion");
        asas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 80, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Cedula");
        asas.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 72, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Apellido");
        asas.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 130, 78, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Telefono");
        asas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 78, -1));

        jtxtApe.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtApe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtApeKeyTyped(evt);
            }
        });
        asas.add(jtxtApe, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 123, 150, 40));

        jtxtNom.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jtxtNom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtNomKeyTyped(evt);
            }
        });
        asas.add(jtxtNom, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 123, 150, 40));

        jtxtDir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jtxtDir.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtxtDirKeyTyped(evt);
            }
        });
        asas.add(jtxtDir, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 200, 150, 40));
        asas.add(jtxtCed, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 150, 40));
        asas.add(jtxtTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 190, 150, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asas, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(asas, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean vacio() {
        if (this.jtxtCed.getText().isBlank() || this.jtxtNom.getText().isBlank()
                || this.jtxtApe.getText().isBlank() || this.jtxtDir.getText().isBlank()
                || this.jtxtTel.getText().isBlank()) {
            JOptionPane.showMessageDialog(null, "Espacios en blanco");
            return false;
        }

        return true;
    }

    private void guardar() {
        if (!this.vacio()) {
            return;
        }
        Estudiante est = new Estudiante(jtxtNom.getText(), jtxtCed.getText(), jtxtApe.getText(), jtxtDir.getText(), jtxtTel.getText());
        est_con.editarEstudiantes(est);
        cargarTabla();
        eliminarCampos();
    }

    private void eliminarCampos() {
        this.jtxtCed.setText("");
        this.jtxtNom.setText("");
        this.jtxtApe.setText("");
        this.jtxtDir.setText("");
        this.jtxtTel.setText("");

    }
    private void JbtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnGuardarActionPerformed
        guardar();
    }//GEN-LAST:event_JbtnGuardarActionPerformed

    private void jtxtNomKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtNomKeyTyped
        char caracter = evt.getKeyChar();

        if (!Character.isLetter(caracter) || jtxtNom.getText().length() >= 15) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtNomKeyTyped

    private void jtxtApeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtApeKeyTyped
        char caracter = evt.getKeyChar();

        if (!Character.isLetter(caracter) || jtxtApe.getText().length() >= 15) {
            evt.consume();
        }    }//GEN-LAST:event_jtxtApeKeyTyped

    private void jtxtDirKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtDirKeyTyped
        char caracter = evt.getKeyChar();

        if (!Character.isLetter(caracter) || jtxtDir.getText().length() >= 25) {
            evt.consume();
        }
    }//GEN-LAST:event_jtxtDirKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbtnGuardar;
    private javax.swing.JPanel asas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtblEstudiantes;
    private javax.swing.JTextField jtxtApe;
    private eddercomponente.EdderComponente jtxtCed;
    private javax.swing.JTextField jtxtDir;
    private javax.swing.JTextField jtxtNom;
    private eddercomponente.EdderComponente jtxtTel;
    // End of variables declaration//GEN-END:variables
}
